select
    match_id,
    cast(strftime(match_date, '%Y%m%d') as integer) as date_id,
    match_datetime,
    match_date,
    competition_id,
    season_id,
    season,
    home_team_id,
    away_team_id,
    matchday,
    home_goals,
    away_goals,
    total_goals,
    home_points,
    away_points,
    goal_difference,
    winner_team_id,
    is_completed,
    is_draw,
    is_home_win,
    is_away_win,
    match_status
from {{ ref('int_match_results') }}
